
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 6.0.x'
  inputs:
    version: 6.0.x
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: CmdLine@1
  displayName: 'Build EF CORE Migrations'
  inputs:
    filename: dotnet
    arguments: 'tool install --global dotnet-ef --version 6.0.0'

- task: CmdLine@1
  displayName: 'Build EF CORE Migrations'
  inputs:
    filename: dotnet
    arguments: 'ef migrations script -p Project -o $(build.artifactstagingdirectory)/migrations/script.sql -i'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'Project'
    Contents: 'StartingData.sql'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'